print("hello")
user_input=input("enter your name:")
print("you entered:",user_input)
course=input("enter your course")
DOB=input("enter your dob")
ROLlNO =input("enter your roll no")
print(course)
print(DOB)
print(ROLLNO)